name: ric
version: 1.0.0
config-version: 2

profile: ric

model-paths: [models]
seed-paths: [seeds]
test-paths: [tests]

target-path: target
clean-targets:
  - target
  - dbt_packages

models:
  ric:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
