select
    run_id,
    extracted_at::timestamptz as extracted_at,
    source_record_id,
    visa_number,
    original_name,
    cnc_agrement_year,
    match_strategy,
    search_url,
    source_url,
    allocine_id,
    allocine_title,
    allocine_url,
    allocine_visa_number,
    release_date_raw,
    release_date,
    duration_raw,
    duration_minutes,
    genres,
    trailer_url,
    direction,
    casting,
    screenwriters,
    production,
    technical_team,
    soundtrack,
    distribution,
    companies,
    lower(scrape_status) as scrape_status,
    error_message,
    record_hash
from {{ source('raw', 'allocine_data') }}
where source_record_id is not null
