services:
  db:
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ric_db
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    volumes:
      - .:/backend
    ports:
      - "5001:5001"
    environment:
      - PYTHONUNBUFFERED=1  # Ensures unbuffered output (useful for logging)
    command: bash # poetry run python app.py
    stdin_open: true    # Open stdin for interactive shell
    tty: true 
    depends_on:
      - db