services:
  db:
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ric_db
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    volumes:
      - .:/backend
    ports:
      - "5001:5001"
    environment:
      - PYTHONUNBUFFERED=1  # Ensures unbuffered output (useful for logging)
      - DATABASE_URL=postgresql+psycopg://postgres:postgres@db:5432/ric_db
    command: ["poetry", "run", "uvicorn", "backend.main:backend", "--host", "0.0.0.0", "--port", "5001", "--reload"]
    depends_on:
      - db