ROLES = [
    { "allocine_name": "Réalisateur", "name": "director", "key_role": True, "inclusive_name": "Réalisateur·rice" },
    { "allocine_name": "Acteur", "name": "actor", "key_role": False, "inclusive_name": "Acteur·rice" },
    { "allocine_name": "Scénariste", "name": "screenwriter", "key_role": True, "inclusive_name": "Scénariste" },
    { "allocine_name": "D'après l'oeuvre de", "name": "based_on_work_by", "key_role": False, "inclusive_name": "D'après l'oeuvre de" },
    { "allocine_name": "Producteur", "name": "producer", "key_role": False, "inclusive_name": "Producteur·rice" },
    { "allocine_name": "Producteur délégué", "name": "executive_producer", "key_role": False, "inclusive_name": "Producteur·rice délégué·e" },
    { "allocine_name": "Coproducteur", "name": "co_producer", "key_role": False, "inclusive_name": "Coproducteur·rice" },
    { "allocine_name": "Directeur de la photographie", "name": "director_of_photography", "key_role": True, "inclusive_name": "Directeur·rice de la photo" },
    { "allocine_name": "1er assistant réalisateur", "name": "first_assistant_director", "key_role": True, "inclusive_name": "Assistant·e à la réalisation" },
    { "allocine_name": "Directeur du casting", "name": "casting_director", "key_role": True, "inclusive_name": "Directeur·rice de casting" },
    { "allocine_name": "Chef monteur", "name": "lead_editor", "key_role": True, "inclusive_name": "Monteur·euse" },
    { "allocine_name": "Chef coiffeur", "name": "head_hair_stylist", "key_role": False, "inclusive_name": "Chef·fe coiffeur·se" },
    { "allocine_name": "Chef costumier", "name": "head_costume_designer", "key_role": True, "inclusive_name": "Costumier·ère" },
    { "allocine_name": "Chef maquilleur", "name": "head_makeup_artist", "key_role": False, "inclusive_name": "Chef·fe maquilleur·euse" },
    { "allocine_name": "Directeur de production", "name": "production_manager", "key_role": True, "inclusive_name": "Directeur·rice de production" },
    { "allocine_name": "Scripte", "name": "script_supervisor", "key_role": False, "inclusive_name": "Scripte" },
    { "allocine_name": "Chef décorateur", "name": "production_designer", "key_role": True, "inclusive_name": "Décorateur·rice" },
    { "allocine_name": "Ingénieur du son", "name": "sound_engineer", "key_role": True, "inclusive_name": "Ingénieur·e du son" },
    { "allocine_name": "Régisseur général", "name": "unit_manager", "key_role": False, "inclusive_name": "Régisseur·euse général·e" },
    { "allocine_name": "Compositeur", "name": "composer", "key_role": True, "inclusive_name": "Auteur·rice de la musique" },
    { "allocine_name": "Attaché de presse", "name": "press_officer", "key_role": False, "inclusive_name": "Attaché·e de presse" },
    { "allocine_name": "Distribution", "name": "distribution", "key_role": False, "inclusive_name": "Distribution" },
    { "allocine_name": "InternationalDistributionExports", "name": "international_distribution_exports", "key_role": False, "inclusive_name": "Distribution Export internationale" },
    { "allocine_name": "Production", "name": "production", "key_role": False, "inclusive_name": "Production" },
    { "allocine_name": "Costumier", "name": "costume_designer", "key_role": False, "inclusive_name": "Costumier·ère" },
    { "allocine_name": "Maquilleur", "name": "makeup_artist", "key_role": False, "inclusive_name": "Maquilleur·euse" },
    { "allocine_name": "CoProduction", "name": "co_production", "key_role": False, "inclusive_name": "Co-Production" },
    { "allocine_name": "Monteur", "name": "editor", "key_role": False, "inclusive_name": "Aide monteur·euse" },
    { "allocine_name": "Dialoguiste", "name": "dialogue_writer", "key_role": False, "inclusive_name": "Dialoguiste" },
    { "allocine_name": "Sur une idée de", "name": "based_on_idea_by", "key_role": False, "inclusive_name": "Sur une idée de" },
    { "allocine_name": "Producteur associé", "name": "associate_producer", "key_role": False, "inclusive_name": "Producteur·rice associé·e" },
    { "allocine_name": "Producteur exécutif", "name": "executive_producer_other", "key_role": False, "inclusive_name": "Producteur·rice exécutif·ve" },
    { "allocine_name": "Superviseur post-production", "name": "post_production_supervisor", "key_role": False, "inclusive_name": "Superviseur·rice post-production" },
    { "allocine_name": "Coordinateur Post-Production", "name": "post_production_coordinator", "key_role": False, "inclusive_name": "Coordinateur·rice Post-Production" },
    { "allocine_name": "Superviseur musical", "name": "music_supervisor", "key_role": False, "inclusive_name": "Superviseur·rice musical·e" },
    { "allocine_name": "Adaptateur", "name": "adapter", "key_role": False, "inclusive_name": "Adaptateur·rice" },
    { "allocine_name": "Cascadeur", "name": "stuntman", "key_role": False, "inclusive_name": "Cascadeur·euse" },
    { "allocine_name": "Musiques additionnelles (compositeur)", "name": "additional_music_composer", "key_role": False, "inclusive_name": "Compositeur·rice de musiques additionnelles" },
    { "allocine_name": "Collaboration au scénario", "name": "screenplay_collaborator", "key_role": False, "inclusive_name": "Collaboration au scénario" },
    { "allocine_name": "1er assistant opérateur", "name": "first_assistant_camera", "key_role": False, "inclusive_name": "1er assistant·e opérateur·rice" },
    { "allocine_name": "Producteur Post-Production", "name": "post_production_producer", "key_role": False, "inclusive_name": "Producteur·rice Post-Production" },
    { "allocine_name": "Assistant réalisateur", "name": "assistant_director", "key_role": False, "inclusive_name": "Assistant·e réalisateur·rice" },
    { "allocine_name": "2ème assistant réalisateur", "name": "second_assistant_director", "key_role": False, "inclusive_name": "2ème assistant·e réalisateur·rice" },
    { "allocine_name": "Monteur son", "name": "sound_editor", "key_role": False, "inclusive_name": "Monteur·euse son" },
    { "allocine_name": "Mixage", "name": "mixing", "key_role": False, "inclusive_name": "Mixage" },
    { "allocine_name": "Etalonneur", "name": "colorist", "key_role": False, "inclusive_name": "Etalonneur·rice" },
    { "allocine_name": "Electricien", "name": "electrician", "key_role": False, "inclusive_name": "Electricien·ne" },
    { "allocine_name": "Producteur des effets visuels", "name": "visual_effects_producer", "key_role": True, "inclusive_name": "Effets spéciaux" },
    { "allocine_name": "Coordinateur de production", "name": "production_coordinator", "key_role": False, "inclusive_name": "Coordinateur·rice de production" },
    { "allocine_name": "Co-scénariste", "name": "co_screenwriter", "key_role": False, "inclusive_name": "Co-scénariste" },
    { "allocine_name": "2ème caméra", "name": "second_camera_operator", "key_role": False, "inclusive_name": "2ème caméra" },
    { "allocine_name": "Superviseur des costumes", "name": "costume_supervisor", "key_role": False, "inclusive_name": "Superviseur·rice des costumes" },
    { "allocine_name": "Directeur artistique", "name": "art_director", "key_role": False, "inclusive_name": "Directeur·rice artistique" },
    { "allocine_name": "Concepteur graphique", "name": "graphic_designer", "key_role": False, "inclusive_name": "Concepteur·rice graphique" },
    { "allocine_name": "Documentation", "name": "documentation", "key_role": False, "inclusive_name": "Documentation" },
    { "allocine_name": "Assistant opérateur", "name": "camera_assistant", "key_role": False, "inclusive_name": "Assistant·e opérateur·rice" },
    { "allocine_name": "Bruiteur", "name": "foley_artist", "key_role": False, "inclusive_name": "Bruiteur·euse" },
    { "allocine_name": "ExecutiveProducer", "name": "executive_producer_other", "key_role": False, "inclusive_name": "Producteur·rice exécutif·ve" },
    { "allocine_name": "Chef accessoiriste", "name": "head_prop_master", "key_role": False, "inclusive_name": "Chef·fe accessoiriste" },
    { "allocine_name": "Assistant monteur", "name": "assistant_editor", "key_role": False, "inclusive_name": "Assistant·e monteur·euse" },
    { "allocine_name": "SoundEngineer", "name": "sound_engineer", "key_role": True, "inclusive_name": "Ingénieur·e du son" },
    { "allocine_name": "Monteur dialogue", "name": "dialogue_editor", "key_role": False, "inclusive_name": "Monteur·euse dialogue" },
    { "allocine_name": "Effets spéciaux maquillage", "name": "special_effects_makeup", "key_role": False, "inclusive_name": "Effets spéciaux maquillage" },
    { "allocine_name": "Effets spéciaux", "name": "special_effects", "key_role": False, "inclusive_name": "Aide aux éffets spéciaux" },
    { "allocine_name": "Coordinateurs effets visuels", "name": "visual_effects_coordinators", "key_role": False, "inclusive_name": "Coordinateurs effets visuels" },
    { "allocine_name": "Choregraphe", "name": "choreographer", "key_role": False, "inclusive_name": "Chorégraphe" },
    { "allocine_name": "Réalisateur de 2nd équipe", "name": "second_unit_director", "key_role": False, "inclusive_name": "Réalisateur·rice de 2nd équipe" },
    { "allocine_name": "Chef Cascadeur", "name": "stunt_coordinator", "key_role": False, "inclusive_name": "Chef·fe Cascadeur·euse" },
    { "allocine_name": "Producteur musical", "name": "music_producer", "key_role": False, "inclusive_name": "Producteur·rice musical·e" },
    { "allocine_name": "Chef électricien", "name": "gaffer", "key_role": False, "inclusive_name": "Chef·fe électricien·ne" },
    { "allocine_name": "Création graphique des personnages", "name": "character_graphic_designer", "key_role": False, "inclusive_name": "Création graphique des personnages" },
    { "allocine_name": "Réalisateur/Concepteur de story-board", "name": "storyboard_director", "key_role": False, "inclusive_name": "Réalisateur·rice/Concepteur·rice de story-board" },
    { "allocine_name": "Conseiller technique", "name": "technical_advisor", "key_role": False, "inclusive_name": "Conseiller·rice technique" },
    { "allocine_name": "Dresseur d'animaux", "name": "animal_trainer", "key_role": False, "inclusive_name": "Dresseur·euse d'animaux" },
    { "allocine_name": "Assistant costumes", "name": "costume_assistant", "key_role": False, "inclusive_name": "Assistant·e costumes" },
    { "allocine_name": "Chef machiniste", "name": "head_grip", "key_role": False, "inclusive_name": "Chef·fe machiniste" },
    { "allocine_name": "Chargé de production", "name": "production_manager_assistant", "key_role": False, "inclusive_name": "Chargé·e de production" },
    { "allocine_name": "Accessoiriste", "name": "prop_master", "key_role": False, "inclusive_name": "Accessoiriste" },
    { "allocine_name": "Coiffeur", "name": "hair_stylist", "key_role": False, "inclusive_name": "Coiffeur·se" },
    { "allocine_name": "Photographe de plateau", "name": "set_photographer", "key_role": False, "inclusive_name": "Photographe de plateau" },
    { "allocine_name": "Coproducteur délégué", "name": "delegate_co_producer", "key_role": False, "inclusive_name": "Coproducteur·rice délégué·e" },
    { "allocine_name": "PrAgency", "name": "pr_agency", "key_role": False, "inclusive_name": "Agence de presse" },
    { "allocine_name": "Superviseur des effets visuels", "name": "visual_effects_supervisor", "key_role": False, "inclusive_name": "Superviseur·rice des effets visuels" },
    { "allocine_name": "Animateur", "name": "animator", "key_role": False, "inclusive_name": "Animateur·rice" },
    { "allocine_name": "Interprète (chansons du film)", "name": "film_song_performer", "key_role": False, "inclusive_name": "Interprète (chansons du film)" },
    { "allocine_name": "Habilleur", "name": "dresser", "key_role": False, "inclusive_name": "Habilleur·se" },
    { "allocine_name": "Assistant décorateur", "name": "assistant_set_designer", "key_role": False, "inclusive_name": "Assistant·e décorateur·rice" },
    { "allocine_name": "Extras casting", "name": "extras_casting", "key_role": False, "inclusive_name": "Extras casting" },
    { "allocine_name": "Repérages", "name": "location_scouting", "key_role": False, "inclusive_name": "Repérages" },
    { "allocine_name": "Directeur artistique effets visuels", "name": "visual_effects_art_director", "key_role": False, "inclusive_name": "Directeur·rice artistique effets visuels" },
    { "allocine_name": "Cadreur", "name": "camera_operator", "key_role": False, "inclusive_name": "Cadreur·euse" },
    { "allocine_name": "Consultant", "name": "consultant", "key_role": False, "inclusive_name": "Consultant·e" },
    { "allocine_name": "Assistant photo", "name": "photo_assistant", "key_role": False, "inclusive_name": "Assistant·e photo" },
    { "allocine_name": "Coach", "name": "coach", "key_role": False, "inclusive_name": "Coach" },
    { "allocine_name": "Photographe", "name": "photographer", "key_role": False, "inclusive_name": "Photographe" },
    { "allocine_name": "3ème assistant réalisateur", "name": "third_assistant_director", "key_role": False, "inclusive_name": "3ème assistant·e réalisateur·rice" },
    { "allocine_name": "Directeur du casting enfants", "name": "child_casting_director", "key_role": False, "inclusive_name": "Directeur·rice du casting enfants" },
    { "allocine_name": "Auteur", "name": "author", "key_role": False, "inclusive_name": "Auteur·rice" },
    { "allocine_name": "Dresseur", "name": "trainer", "key_role": False, "inclusive_name": "Dresseur·euse" },
    { "allocine_name": "Machiniste", "name": "grip", "key_role": False, "inclusive_name": "Machiniste" },
    { "allocine_name": "Peintre", "name": "painter", "key_role": False, "inclusive_name": "Peintre" },
    { "allocine_name": "Parolier", "name": "lyricist", "key_role": False, "inclusive_name": "Parolier·ère" },
    { "allocine_name": "Press", "name": "press_contact", "key_role": False, "inclusive_name": "Contact presse" },
    { "allocine_name": "2ème assistant opérateur", "name": "second_camera_assistant", "key_role": False, "inclusive_name": "2ème assistant·e opérateur·rice" },
    { "allocine_name": "Repéreur", "name": "location_scout", "key_role": False, "inclusive_name": "Repéreur·euse" },
    { "allocine_name": "Collaborateur artistique", "name": "artistic_collaborator", "key_role": False, "inclusive_name": "Collaborateur·rice artistique" },
    { "allocine_name": "Enregistreur de bruitages", "name": "foley_recorder", "key_role": False, "inclusive_name": "Enregistreur·euse de bruitages" },
    { "allocine_name": "Directeur de l'animation", "name": "animation_director", "key_role": False, "inclusive_name": "Directeur·rice de l'animation" },
    { "allocine_name": "Musique du générique", "name": "credits_music", "key_role": False, "inclusive_name": "Musique du générique" },
    { "allocine_name": "Layout", "name": "layout_artist", "key_role": False, "inclusive_name": "Layout" },
    { "allocine_name": "Administrateur de Production", "name": "production_administrator", "key_role": False, "inclusive_name": "Administrateur·rice de Production" },
    { "allocine_name": "Secrétaire de production", "name": "production_secretary", "key_role": False, "inclusive_name": "Secrétaire de production" },
    { "allocine_name": "MusicalSupervisor", "name": "musical_supervisor", "key_role": False, "inclusive_name": "Superviseur·euse musical·e" },
    { "allocine_name": "Réalisateur du making of", "name": "making_of_director", "key_role": False, "inclusive_name": "Réalisateur·rice du making of" },
    { "allocine_name": "Coordinateur des combats", "name": "fight_coordinator", "key_role": False, "inclusive_name": "Coordinateur·rice des combats" },
    { "allocine_name": "Assistant son", "name": "sound_assistant", "key_role": False, "inclusive_name": "Assistant·e son" },
    { "allocine_name": "Superviseur animation des personnages", "name": "character_animation_supervisor", "key_role": False, "inclusive_name": "Superviseur·euse animation des personnages" },
    { "allocine_name": "Compositeur (chansons du film)", "name": "song_composer", "key_role": False, "inclusive_name": "Compositeur·rice (chansons du film)" },
    { "allocine_name": "AnimationStudio", "name": "animation_studio", "key_role": False, "inclusive_name": "Studio d'animation" },
    { "allocine_name": "Assistant de production", "name": "production_assistant", "key_role": False, "inclusive_name": "Assistant·e de production" },
    { "allocine_name": "Responsable des effets sonores", "name": "sound_effects_supervisor", "key_role": False, "inclusive_name": "Responsable des effets sonores" },
    { "allocine_name": "Concepteur artistique", "name": "artistic_designer", "key_role": False, "inclusive_name": "Concepteur·rice artistique" },
    { "allocine_name": "Superviseur compositing", "name": "compositing_supervisor", "key_role": False, "inclusive_name": "Superviseur·euse compositing" },
    { "allocine_name": "Assistant maquillage", "name": "makeup_assistant", "key_role": False, "inclusive_name": "Assistant·e maquillage" },
    { "allocine_name": "Marionnettiste", "name": "puppeteer", "key_role": False, "inclusive_name": "Marionnettiste" },
    { "allocine_name": "Scénariste (version originale)", "name": "original_version_screenwriter", "key_role": False, "inclusive_name": "Scénariste (version originale)" },
    { "allocine_name": "Directeur de la photographie de la seconde équipe", "name": "second_unit_dop", "key_role": False, "inclusive_name": "Directeur·rice de la photographie de la seconde équipe" },
    { "allocine_name": "Chef constructeur", "name": "head_builder", "key_role": False, "inclusive_name": "Chef·fe constructeur·rice" },
    { "allocine_name": "Directeur technique", "name": "technical_director", "key_role": False, "inclusive_name": "Directeur·rice technique" },
    { "allocine_name": "D'après les personnages créés par", "name": "based_on_characters_by", "key_role": False, "inclusive_name": "D'après les personnages créés par" },
    { "allocine_name": "Superviseur du design sonore", "name": "sound_design_supervisor", "key_role": False, "inclusive_name": "Superviseur·euse du design sonore" },
    { "allocine_name": "Création sonore", "name": "sound_creation", "key_role": False, "inclusive_name": "Création sonore" },
    { "allocine_name": "Responsable de la Production", "name": "production_head", "key_role": False, "inclusive_name": "Responsable de la Production" },
    { "allocine_name": "Conception générique", "name": "credits_design", "key_role": False, "inclusive_name": "Conception générique" },
    { "allocine_name": "Mixage musical", "name": "music_mixing", "key_role": False, "inclusive_name": "Mixage musical" },
    { "allocine_name": "Modélisation", "name": "modeling", "key_role": False, "inclusive_name": "Modélisation" },
    { "allocine_name": "SpecialEffects", "name": "special_effects", "key_role": False, "inclusive_name": "Aide aux éffets spéciaux" },
    { "allocine_name": "Régleur cascades", "name": "stunt_coordinator_assistant", "key_role": False, "inclusive_name": "Régleur·euse cascades" },
    { "allocine_name": "Monteur associé", "name": "associate_editor", "key_role": False, "inclusive_name": "Monteur·euse associé·e" },
    { "allocine_name": "Perchman", "name": "boom_operator", "key_role": False, "inclusive_name": "Perchman" },
    { "allocine_name": "Chanteur", "name": "singer", "key_role": False, "inclusive_name": "Chanteur·euse" },
    { "allocine_name": "Eclairages", "name": "lighting", "key_role": False, "inclusive_name": "Eclairages" },
    { "allocine_name": "Créateur", "name": "creator", "key_role": False, "inclusive_name": "Créateur·rice" },
    { "allocine_name": "Superviseur du layout", "name": "layout_supervisor", "key_role": False, "inclusive_name": "Superviseur·euse du layout" },
    { "allocine_name": "Décors couleurs", "name": "color_set_design", "key_role": False, "inclusive_name": "Décors couleurs" },
    { "allocine_name": "Montage musical", "name": "music_editing", "key_role": False, "inclusive_name": "Montage musical" },
    { "allocine_name": "FilmExhibitor", "name": "film_exhibitor", "key_role": False, "inclusive_name": "Exploitation cinématographique" },
    { "allocine_name": "Coach sportif", "name": "sports_coach", "key_role": False, "inclusive_name": "Coach sportif" },
    { "allocine_name": "Monteur des effets sonores", "name": "sound_effects_editor", "key_role": False, "inclusive_name": "Monteur·euse des effets sonores" },
    { "allocine_name": "Assistant Régisseur général", "name": "assistant_unit_manager", "key_role": False, "inclusive_name": "Assistant·e Régisseur·euse général·e" },
    { "allocine_name": "Superviseur de la 3D", "name": "3d_supervisor", "key_role": False, "inclusive_name": "Superviseur·euse de la 3D" },
    { "allocine_name": "Musiques additionnelles (interprète)", "name": "additional_music_performer", "key_role": False, "inclusive_name": "Interprète de musiques additionnelles" },
    { "allocine_name": "Répétiteur enfants", "name": "child_rehearsal_coach", "key_role": False, "inclusive_name": "Répétiteur·rice enfants" },
    { "allocine_name": "Superviseur technique", "name": "technical_supervisor", "key_role": False, "inclusive_name": "Superviseur·euse technique" },
    { "allocine_name": "Images sous-marine", "name": "underwater_cinematographer", "key_role": False, "inclusive_name": "Images sous-marine" },
    { "allocine_name": "Chef éclairagiste", "name": "head_lighting_technician", "key_role": False, "inclusive_name": "Chef·fe éclairagiste" },
    { "allocine_name": "Coordinateur de la musique", "name": "music_coordinator", "key_role": False, "inclusive_name": "Coordinateur·rice de la musique" },
    { "allocine_name": "PostProduction", "name": "post_production", "key_role": False, "inclusive_name": "Post-Production" },
    { "allocine_name": "VisualEffects", "name": "visual_effects", "key_role": False, "inclusive_name": "Effets visuels" },
    { "allocine_name": "Effets spéciaux 2D", "name": "special_effects_2d", "key_role": False, "inclusive_name": "Effets spéciaux 2D" },
    { "allocine_name": "Conseiller musical", "name": "music_consultant", "key_role": False, "inclusive_name": "Conseiller·e musical·e" },
    { "allocine_name": "Superviseur de la mise en couleur des personnages", "name": "character_color_supervisor", "key_role": False, "inclusive_name": "Superviseur·euse de la mise en couleur des personnages" },
    { "allocine_name": "Musicien", "name": "musician", "key_role": False, "inclusive_name": "Musicien·ne" },
    { "allocine_name": "Responsable Casting", "name": "casting_manager", "key_role": False, "inclusive_name": "Responsable Casting" },
    { "allocine_name": "Dessinateur", "name": "illustrator", "key_role": False, "inclusive_name": "Dessinateur·rice" },
    { "allocine_name": "Stéréographie", "name": "stereography", "key_role": False, "inclusive_name": "Stéréographie" },
    { "allocine_name": "Monteur bruitages", "name": "sound_fx_editor", "key_role": False, "inclusive_name": "Monteur·euse bruitages" },
    { "allocine_name": "Conseiller aux dialogues", "name": "dialogue_coach", "key_role": False, "inclusive_name": "Conseiller·e aux dialogues" },
    { "allocine_name": "Concepteur d'affiche", "name": "poster_designer", "key_role": False, "inclusive_name": "Concepteur·rice d'affiche" },
    { "allocine_name": "Responsable de la Fiction", "name": "fiction_head", "key_role": False, "inclusive_name": "Responsable de la Fiction" },
    { "allocine_name": "Assistant coordinateur de production", "name": "assistant_production_coordinator", "key_role": False, "inclusive_name": "Assistant·e coordinateur·rice de production" },
    { "allocine_name": "Superviseur artistique", "name": "art_supervisor", "key_role": False, "inclusive_name": "Superviseur·euse artistique" },
    { "allocine_name": "Superviseur de l'infographie", "name": "graphics_supervisor", "key_role": False, "inclusive_name": "Superviseur·euse de l'infographie" },
    { "allocine_name": "Directeur d’écriture", "name": "writing_director", "key_role": False, "inclusive_name": "Directeur·rice d’écriture" },
    { "allocine_name": "Compositeur de la partition originale", "name": "original_score_composer", "key_role": False, "inclusive_name": "Compositeur·rice de la partition originale" },
    { "allocine_name": "TvChannel", "name": "tv_channel", "key_role": False, "inclusive_name": "Chaîne de télévision" },
    { "allocine_name": "SoundEditor", "name": "sound_editor", "key_role": False, "inclusive_name": "Monteur·euse son" },
    { "allocine_name": "Assistant directeur artistique", "name": "assistant_art_director", "key_role": False, "inclusive_name": "Assistant·e directeur·rice artistique" },
    { "allocine_name": "Assistant ensemblier", "name": "set_dresser_assistant", "key_role": False, "inclusive_name": "Assistant·e ensemblier·ère" },
    { "allocine_name": "Assistant Régisseur (renfort)", "name": "assistant_unit_manager_backup", "key_role": False, "inclusive_name": "Assistant·e Régisseur·euse (renfort)" },
    { "allocine_name": "Responsable de la distribution et des ventes internationales", "name": "intl_distribution_manager", "key_role": False, "inclusive_name": "Responsable de la distribution et des ventes internationales" },
    { "allocine_name": "Développement visuel", "name": "visual_development", "key_role": False, "inclusive_name": "Développement visuel" },
    { "allocine_name": "Armurier", "name": "armorer", "key_role": False, "inclusive_name": "Armurier·ère" },
    { "allocine_name": "Coordinateur des combats adjoint", "name": "fight_coordinator_assistant", "key_role": False, "inclusive_name": "Coordinateur·rice des combats adjoint·e" },
    { "allocine_name": "Peinture des mattes", "name": "matte_painter", "key_role": False, "inclusive_name": "Peinture des mattes" },
    { "allocine_name": "Styliste", "name": "stylist", "key_role": False, "inclusive_name": "Styliste" },
    { "allocine_name": "Prise de vues aériennes", "name": "aerial_cinematography", "key_role": False, "inclusive_name": "Prise de vues aériennes" },
    { "allocine_name": "assistant de l’ingénieur du son de la post-synchronisation", "name": "post_sync_sound_assistant", "key_role": False, "inclusive_name": "Assistant·e de l’ingénieur·e du son de la post-synchronisation" },
    { "allocine_name": "Directeur général", "name": "general_manager", "key_role": False, "inclusive_name": "Directeur·rice général·e" },
    { "allocine_name": "Assistant régisseur adjoint", "name": "assistant_unit_manager_deputy", "key_role": False, "inclusive_name": "Assistant·e régisseur·euse adjoint·e" },
    { "allocine_name": "Conseiller juridique", "name": "legal_advisor", "key_role": False, "inclusive_name": "Conseiller·e juridique" },
    { "allocine_name": "Coordinateur des cascades adjoint", "name": "stunt_coord_assistant", "key_role": False, "inclusive_name": "Coordinateur·rice des cascades adjoint·e" },
    { "allocine_name": "Coaching voix", "name": "voice_coach", "key_role": False, "inclusive_name": "Coaching voix" },
    { "allocine_name": "Restauration du son", "name": "sound_restoration", "key_role": False, "inclusive_name": "Restauration du son" },
    { "allocine_name": "Monteur effets visuels", "name": "vfx_editor", "key_role": False, "inclusive_name": "Monteur·euse effets visuels" },
    { "allocine_name": "Texturation", "name": "texturing", "key_role": False, "inclusive_name": "Texturation" },
    { "allocine_name": "Relations Publiques", "name": "public_relations", "key_role": False, "inclusive_name": "Relations Publiques" },
    { "allocine_name": "\"Interprète (chansons du film, version française)\"", "name": "french_version_song_performer", "key_role": False, "inclusive_name": "Interprète (chansons du film, version française)" },
    { "allocine_name": "Superviseur montage dialogues", "name": "dialogue_editing_supervisor", "key_role": False, "inclusive_name": "Superviseur·euse montage dialogues" },
    { "allocine_name": "Directeur de la photographie des effets visuels", "name": "vfx_dop", "key_role": False, "inclusive_name": "Directeur·rice de la photographie des effets visuels" },
    { "allocine_name": "Images animalières", "name": "wildlife_cinematography", "key_role": False, "inclusive_name": "Images animalières" },
]
