"""Add allocine_name to roles

Revision ID: 165c9a285a71
Revises: 4ccb0b5574a8
Create Date: 2025-04-18 13:33:28.778410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '165c9a285a71'
down_revision: Union[str, None] = '4ccb0b5574a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ric_roles', sa.Column('allocine_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ric_roles', 'allocine_name')
    # ### end Alembic commands ###
