"""Create trailer characters table

Revision ID: 1b85fcd5a62e
Revises: 165c9a285a71
Create Date: 2025-04-20 17:59:30.459722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b85fcd5a62e'
down_revision: Union[str, None] = '165c9a285a71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ric_trailer_characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trailer_id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('age_min', sa.Integer(), nullable=True),
    sa.Column('age_max', sa.Integer(), nullable=True),
    sa.Column('ethnicity', sa.String(), nullable=True),
    sa.Column('time_on_screen', sa.Float(), nullable=True),
    sa.Column('average_size_on_screen', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['trailer_id'], ['ric_trailers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ric_trailer_characters')
    # ### end Alembic commands ###
