"""Create award_nominations table

Revision ID: 230802dd9cec
Revises: 6df58c273a80
Create Date: 2025-03-17 20:10:42.337002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '230802dd9cec'
down_revision: Union[str, None] = '6df58c273a80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ric_award_nominations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.Column('credit_holder_id', sa.Integer(), nullable=True),
    sa.Column('award_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('is_winner', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['award_id'], ['ric_festival_awards.id'], ),
    sa.ForeignKeyConstraint(['credit_holder_id'], ['ric_credit_holders.id'], ),
    sa.ForeignKeyConstraint(['film_id'], ['ric_films.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ric_award_nominations')
    # ### end Alembic commands ###
