"""Add inclusive name to roles

Revision ID: 4bd9e4bb5bc3
Revises: c6fb92e4e96f
Create Date: 2025-06-06 15:41:36.118793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bd9e4bb5bc3'
down_revision: Union[str, None] = 'c6fb92e4e96f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ric_roles', sa.Column('inclusive_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ric_roles', 'inclusive_name')
    # ### end Alembic commands ###
