"""Add attributes to festival_awards

Revision ID: 6352fe8a8250
Revises: 9acf3149fef3
Create Date: 2025-06-20 12:57:04.919176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6352fe8a8250'
down_revision: Union[str, None] = '9acf3149fef3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ric_festival_awards', sa.Column('mubi_label', sa.String(), nullable=False))
    op.add_column('ric_festival_awards', sa.Column('english_label', sa.String(), nullable=True))
    op.add_column('ric_festival_awards', sa.Column('french_label', sa.String(), nullable=True))
    op.drop_column('ric_festival_awards', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ric_festival_awards', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('ric_festival_awards', 'french_label')
    op.drop_column('ric_festival_awards', 'english_label')
    op.drop_column('ric_festival_awards', 'mubi_label')
    # ### end Alembic commands ###
