"""Create festival_awards table

Revision ID: 6df58c273a80
Revises: 52f50b4aed4f
Create Date: 2025-03-17 20:06:07.523918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6df58c273a80'
down_revision: Union[str, None] = '52f50b4aed4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('festival_awards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('festival_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['festival_id'], ['festivals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('festival_awards')
    # ### end Alembic commands ###
