"""Add additional attributes to films

Revision ID: 9acf3149fef3
Revises: 4bd9e4bb5bc3
Create Date: 2025-06-15 14:12:06.801524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9acf3149fef3'
down_revision: Union[str, None] = '4bd9e4bb5bc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ric_films', sa.Column('mubi_id', sa.Integer(), nullable=True))
    op.add_column('ric_films', sa.Column('budget_category', sa.String(), nullable=True))
    op.add_column('ric_films', sa.Column('genre_categories', sa.String(), nullable=True))
    op.add_column('ric_films', sa.Column('broadcasters', sa.String(), nullable=True))
    op.add_column('ric_films', sa.Column('is_french_financed', sa.Boolean(), nullable=True))
    op.drop_column('ric_films', 'first_language')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ric_films', sa.Column('first_language', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('ric_films', 'is_french_financed')
    op.drop_column('ric_films', 'broadcasters')
    op.drop_column('ric_films', 'genre_categories')
    op.drop_column('ric_films', 'budget_category')
    op.drop_column('ric_films', 'mubi_id')
    # ### end Alembic commands ###
