"""Create films_genres table

Revision ID: a41a851372bf
Revises: 8babdd0aeb7b
Create Date: 2025-03-16 16:24:04.683032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a41a851372bf'
down_revision: Union[str, None] = '8babdd0aeb7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ric_films_genres',
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['ric_films.id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['ric_genres.id'], ),
    sa.PrimaryKeyConstraint('film_id', 'genre_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ric_films_genres')
    # ### end Alembic commands ###
