"""Create credit_holders table

Revision ID: b0c6222108ff
Revises: 9cf40267d373
Create Date: 2025-03-17 19:42:40.858524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0c6222108ff'
down_revision: Union[str, None] = '9cf40267d373'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ric_credit_holders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('Company', 'Individual', name='credit_holder_type'), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('legal_name', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ric_credit_holders')
    # Explicitly drop the enum type
    op.execute("DROP TYPE IF EXISTS credit_holder_type")
    # ### end Alembic commands ###
