"""Create poster characters table

Revision ID: c6fb92e4e96f
Revises: 1b85fcd5a62e
Create Date: 2025-04-20 18:02:10.940210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6fb92e4e96f'
down_revision: Union[str, None] = '1b85fcd5a62e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ric_poster_characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poster_id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('age_min', sa.Integer(), nullable=True),
    sa.Column('age_max', sa.Integer(), nullable=True),
    sa.Column('ethnicity', sa.String(), nullable=True),
    sa.Column('poster_percentage', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['poster_id'], ['ric_posters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ric_poster_characters')
    # ### end Alembic commands ###
