"""Create film_credits table

Revision ID: d5ecbb43840b
Revises: b0c6222108ff
Create Date: 2025-03-17 19:48:38.487224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5ecbb43840b'
down_revision: Union[str, None] = 'b0c6222108ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ric_film_credits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('credit_holder_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['credit_holder_id'], ['ric_credit_holders.id'], ),
    sa.ForeignKeyConstraint(['film_id'], ['ric_films.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['ric_roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ric_film_credits')
    # ### end Alembic commands ###
