"""Create films table

Revision ID: e9f855b8ad1c
Revises: 
Create Date: 2025-03-16 16:02:05.446440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9f855b8ad1c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('films',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('original_name', sa.String(), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('first_language', sa.String(), nullable=True),
    sa.Column('tmdb_id', sa.Integer(), nullable=True),
    sa.Column('budget', sa.Float(), nullable=True),
    sa.Column('bechdel_compliant', sa.Boolean(), nullable=True),
    sa.Column('parity_bonus', sa.Boolean(), nullable=True),
    sa.Column('eof', sa.Boolean(), nullable=True),
    sa.Column('asr', sa.Boolean(), nullable=True),
    sa.Column('sofica_funding', sa.Boolean(), nullable=True),
    sa.Column('tax_credit', sa.Boolean(), nullable=True),
    sa.Column('regional_funding', sa.Boolean(), nullable=True),
    sa.Column('cnc_agrement_year', sa.Date(), nullable=True),
    sa.Column('cnc_rank', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('films')
    # ### end Alembic commands ###
